/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.usefultoys.rcp.security.ui;

import org.usefultoys.rcp.platform.dialog.api.DialogConvention;
import org.usefultoys.rcp.security.api.AuthenticatedUser;
import java.awt.Component;
import org.openide.util.NbBundle;
import org.usefultoys.rcp.platform.dialog.core.DialogConventionDefault;

/**
 *
 * @author Daniel Felix Ferber
 */
@NbBundle.Messages({
    "UserPropertiesPanel_Message_Default=User information"
})
public class UserPropertiesPanel extends javax.swing.JPanel implements DialogConvention.Support<UserPropertiesPanel.Inbound, UserPropertiesPanel.Outbound> {

    private final Descriptor descriptor;
    private final DialogConventionImpl dialogConvention;

    /**
     * Describes how to build the panel.
     */
    public static class Descriptor {

        boolean editableProperties;
        public boolean editableLogin;
        public boolean editableName;
        public boolean editablePassword;
        public String defaultMessage = Bundle.UserPropertiesPanel_Message_Default();
    }

    public interface Validation {

        String validateLoginCandidate(String candidate) throws IllegalStateException;
    }

    public static class Inbound {

        public String login;
        public String name;

        public Inbound() {
            super();
        }

        public void fromObject(AuthenticatedUser authenticatedUser) {
            if (authenticatedUser == null) {
                throw new IllegalArgumentException("authenticatedUser == null");
            }
            login = authenticatedUser.getLogin();
            name = authenticatedUser.getName();
        }
    }

    public static class Outbound {

        public String login;
        public String name;
    }

    /**
     * Creates new form UserPropertiesPanel
     */
    public UserPropertiesPanel(Descriptor descriptor) {
        this.descriptor = descriptor;
        initComponents();
        this.dialogConvention = new DialogConventionImpl(this, descriptor.defaultMessage);
        updateFieldEditable();
    }

    private class DialogConventionImpl extends DialogConventionDefault<Inbound, Outbound> {

        public DialogConventionImpl(Component source, String defaultMessage) {
            super(source, defaultMessage);
        }

        @Override
        public Inbound createInbound() {
            return new Inbound();
        }

        @Override
        public Outbound createOutbound() {
            return new Outbound();
        }

        @Override
        protected void convertInboundToFields(Inbound inbound) {
            loginField.setText(inbound.login);
            nameField.setText(inbound.name);
        }
    }

    @Override
    public DialogConvention getDialogConvention() {
        return dialogConvention;
    }

    private void updateFieldEditable() {
        boolean enabled = super.isEnabled();
        this.passwordButton.setEnabled(descriptor.editablePassword && enabled);
        this.loginField.setEditable(descriptor.editableProperties && descriptor.editableLogin && enabled);
        this.nameField.setEditable(descriptor.editableProperties && descriptor.editableName && enabled);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        loginField = new javax.swing.JTextField();
        passwordButton = new javax.swing.JToggleButton();
        nameField = new javax.swing.JTextField();

        org.openide.awt.Mnemonics.setLocalizedText(loginLabel, org.openide.util.NbBundle.getMessage(UserPropertiesPanel.class, "UserPropertiesPanel.loginLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(nameLabel, org.openide.util.NbBundle.getMessage(UserPropertiesPanel.class, "UserPropertiesPanel.nameLabel.text")); // NOI18N

        loginField.setText(org.openide.util.NbBundle.getMessage(UserPropertiesPanel.class, "UserPropertiesPanel.loginField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(passwordButton, org.openide.util.NbBundle.getMessage(UserPropertiesPanel.class, "UserPropertiesPanel.passwordButton.text")); // NOI18N
        passwordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordButtonActionPerformed(evt);
            }
        });

        nameField.setText(org.openide.util.NbBundle.getMessage(UserPropertiesPanel.class, "UserPropertiesPanel.nameField.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(loginLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loginField, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passwordButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameField)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginLabel)
                    .addComponent(loginField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void passwordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordButtonActionPerformed
        UserPasswordAction.runAction(this);
    }//GEN-LAST:event_passwordButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField loginField;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JToggleButton passwordButton;
    // End of variables declaration//GEN-END:variables
}
