package br.com.danielferber.rcp.securitytoys.ui;

/**
 *
 * @author X7WS
 */
public class CredentialPanel extends javax.swing.JPanel {

    public static final String PROP_PREFIXO = CredentialPanel.class.getName()+".";
    public static final String PROP_SENHA = PROP_PREFIXO + "senha";
    public static final String PROP_CHAVE = PROP_PREFIXO + "chave";
    
    /**
     * Creates new form CredenciaisPanel
     */
    public CredentialPanel(String login) {
        initComponents();
        campoLogin.setText(login);
    }
    
    public String getLogin() {
        return campoLogin.getText();
    }
    
    public char[] getSenha() {
        return campoSenha.getPassword();
    }
    
    public void apagarSenha() {
        campoSenha.setText("");
        firePropertyChange(PROP_SENHA, null, null);
    }
    
    public void setLogin(final String login) {
        final String chaveAntiga = campoLogin.getText();
        campoLogin.setText(login);
        firePropertyChange(PROP_CHAVE, chaveAntiga, login);
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        campoLogin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoSenha = new javax.swing.JPasswordField();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(CredentialPanel.class, "CredentialPanel.jLabel1.text")); // NOI18N

        campoLogin.setText(org.openide.util.NbBundle.getMessage(CredentialPanel.class, "CredentialPanel.campoLogin.text")); // NOI18N
        campoLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoLoginActionPerformed(evt);
            }
        });
        campoLogin.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                campoLoginPropertyChange(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(CredentialPanel.class, "CredentialPanel.jLabel2.text")); // NOI18N

        campoSenha.setText(org.openide.util.NbBundle.getMessage(CredentialPanel.class, "CredentialPanel.campoSenha.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoLogin))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoSenha)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void campoLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoLoginActionPerformed
    }//GEN-LAST:event_campoLoginActionPerformed

    private void campoLoginPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_campoLoginPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_campoLoginPropertyChange

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoLogin;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
